export const REQUEST_FORECAST = 'fetch/REQUEST_FORECAST'
export const REQUEST_FAILED = 'fetch/REQUEST_FAILED'
export const REQUEST_SUCCESS = 'fetch/REQUEST_SUCCESS'
export const SELECT_LOCATION = 'search/SELECT_LOCATION'
