export const ADD_FORECAST_SEARCH = 'historyTable/ADD_FORECAST_SEARCH'
export const REMOVE_FORECAST_SEARCH = 'historyTable/REMOVE_FORECAST_SEARCH'
export const UPDATE_FORECAST_SEARCH = 'historyTable/UPDATE_FORECAST_SEARCH'
